---
title: "ECON 444 Problem Set 5"
subtitle: "Joseph Sepich April 19"
output:
  pdf_document:
    toc: false
    toc_depth: 2
    number_sections: true
    keep_tex: false
---

# Problem 1

Problem Constrains:

* Cournot Competition (quantity static)
* Market Demand: $P = 10 - 2Q$
* $\text{MC}_1 = 2$
* $\text{MC}_2 = 4$
* $Q = q_1 + q_2$

## Part a

To find best response behavior of each firm, we acknowledge that the firms wish to set MR equal to MC to optimize profits.

\[MR = p*q\]
\[MR_1 = \frac{d((10 - 2(q_1 + q_2)) * q_1)}{dq_1} = \frac{d(10q_1 - 2q_1^2-2q_1q_2)}{dq_1} = 10 - 4q_1 - 2q_2\]
\[MR_2 = \frac{d((10 - 2(q_1 + q_2)) * q_2)}{dq_2} = \frac{d(10q_2 - 2q_2^2-2q_2q_1)}{dq_2} = 10 - 4q_2 - 2q_1\]

Best Response for firm 1:

\[MR_1 = MC_1\]
\[10 - 4q_1 - 2q_2 = 2\]
\[4q_1 = 10 - 2q_2 - 2\]
\[q_1^* = \frac14(8 - 2q_2)\]

Best Response for firm 2:

\[MR_2 = MC_2\]
\[10 - 4q_2 - 2q_1 = 4\]
\[4q_2 = 10 - 2q_1 - 4\]
\[q_2^* = \frac14(6 - 2q_1)\]

## Part b

To find equilibrium we must solve our system of best response equations.

\[4q_1 = 8 - 2 (\frac14(6 - 2q_1))\]
\[16q_1 = 32 - 2(6 - q_1)\]
\[16q_1 = 32 - 12 + 2q_1\]
\[14q_1 = 20\]
\[q_1^* = \frac{20}{14} = \frac{10}7\]

We can plug this back in to solve for firm 2.

\[q_2 = \frac14(6 - 2\frac{20}{14})\]
\[56q_2 = 84 - 40\]
\[56q_2 = 44\]
\[q_2* = \frac{11}{14}\]

\[Q^* = q_1^* + q_2^* = \frac{20 + 11}{14} = \frac{31}{14}\]
\[P^* = 10 - 2Q^* = 10 - \frac{31}{7} = \frac{39}{7} \approx 5.57\]

## Part c

\[\text{Markup:}\frac{p-c}{p}\]

\[m_1 = \frac{p-MC_1}{p} = \frac{5.57 - 2}{5.57} \approx 0.64\]
\[m_1 = \frac{p-MC_2}{p} = \frac{5.57 - 4}{5.57} \approx 0.28\]

The markup in equilibrium for firm 1 is **0.64** and **0.28** for firm 2.

## Part d

\[P = 10-2Q = 10-2(q_1 + q_2)\]

Firm 1 residual demand according to best response:

\[P = 10-2(q_1 + q_2*) = 10 - 2q_1 - 2(\frac{11}{14}) = 10 - \frac{11}{7} - 2q_1\]
\[q_1 = \frac12(8.43 - P)\]

Firm 2 residual demand according to best response:

\[P = 10-2(q_2 + \frac{20}{14}) = 10 - \frac{20}{7}-2q_2\]
\[q_2 = \frac12(7.14 - P)\]

The slope of residual demand is **-2** for both firm 1 and 2. (Inverse market demand curve)

## Part e

Recall the elasticity of demand.

\[\epsilon = \frac{dQ}{dP}\frac{P}{Q}\]

\[\epsilon = \frac{-P}{2Q} = \frac{-5.57}{2(q)}\]

\[\epsilon_1 = \frac{-5.57}{2(1.43)} = -1.95\]
\[\epsilon_2 = \frac{-5.57}{2(0.786)} = -3.54\]

The residual demand elasticity for firm 1 is **-1.95** and **-3.54** for firm 2. The firm with the smaller market share has larger residual demand elasticity. If the firm supplying less decides to supply more, then there will be a greater effect on decrease in prices.

## Part f

The markup does not equal the inverse of residual demand elasticity for either firm.

# Problem 2

# Problem 3

## Part a

## Part b

# Problem 4

## Part a

## Part b

## Part c

# Problem 5

## Part a

## Part b









